name: Disable Checking ServerName

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: modify
        run: |
          cd tailscale
          sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Runs a single command using the runners shell
      - name: Build and push Docker images to ghcr.io
        uses: docker/build-push-action@v6
        with:
          file: 'Dockerfile'
          platforms: linux/amd64,linux/arm64
          context: ./
          push: true
          tags: |
            ghcr.io/jiz4oh/derper:latest
